-- MatchDay — APNs device tokens, alongside the Web Push subscriptions.
--
-- ── ONE TABLE, TWO TRANSPORTS ──────────────────────────────────────────────
--
-- A second table would have meant a second RLS policy, a second column grant, a
-- second set of delivery bookkeeping and a `push_delivery_attempts` foreign key
-- that could point at either — and the dispatcher would still have had to union
-- them back together on every send. Everything that makes a push subscription
-- *a push subscription* is shared: who owns it, whether it is enabled, how many
-- times in a row it has failed, when it was last seen. Only the address differs.
--
-- So `channel` discriminates, and a check constraint makes the two shapes
-- mutually exclusive rather than merely conventional.
--
-- ── THE EXISTING COLUMNS BECOME NULLABLE ───────────────────────────────────
--
-- `endpoint`, `p256dh` and `auth_secret` are Web Push concepts. An APNs row has
-- no endpoint URL and no encryption keys, and storing a placeholder to satisfy
-- a NOT NULL would be a lie that every future reader has to know about. The
-- NOT NULLs move into the channel-conditional check, which states the same
-- guarantee more precisely: web_push rows still cannot be missing any of them.

alter table public.push_subscriptions
  alter column endpoint drop not null,
  alter column p256dh drop not null,
  alter column auth_secret drop not null;

-- The three shape checks predate nullability and would now reject a valid APNs
-- row outright. Each is replaced by a null-tolerant form; the channel check
-- below is what guarantees a web_push row cannot exploit that tolerance.
alter table public.push_subscriptions
  drop constraint push_subscriptions_endpoint_shape,
  drop constraint push_subscriptions_p256dh_length,
  drop constraint push_subscriptions_auth_length;

alter table public.push_subscriptions
  add constraint push_subscriptions_endpoint_shape
    check (endpoint is null
           or (endpoint ~ '^https://' and char_length(endpoint) between 20 and 2048)),
  add constraint push_subscriptions_p256dh_length
    check (p256dh is null or char_length(p256dh) between 16 and 256),
  add constraint push_subscriptions_auth_length
    check (auth_secret is null or char_length(auth_secret) between 8 and 256);


-- ── The new columns ────────────────────────────────────────────────────────

alter table public.push_subscriptions
  -- Defaulted, so every row that existed before this migration is correctly
  -- labelled without an UPDATE, and so `register_push_subscription` keeps
  -- working untouched.
  add column channel public.push_channel not null default 'web_push',

  -- The bearer credential, exactly as `endpoint` is for Web Push: anyone
  -- holding it plus MatchDay's APNs key can put a notification on that lock
  -- screen. Never granted to any client role — see the grant at the foot.
  add column device_token text,

  add column apns_environment public.apns_environment,

  -- Which *installation* of the app this row belongs to, generated by the app
  -- and stable for as long as it stays installed.
  --
  -- This exists because the device token is not a stable identity. APNs rotates
  -- it — on restore from backup, on some OS upgrades, and at its own
  -- discretion — and a rotated token is simply a new value, so nothing about
  -- re-registering it would collide with the row holding the old one. Without a
  -- separate identity for the installation, every rotation would leave an
  -- orphan row addressed to a token that no longer resolves, and the player
  -- would accumulate dead devices they never added.
  --
  -- It is also what sign-out can act on. At sign-out the app knows which
  -- installation it is; it does not necessarily hold a current token, and
  -- asking APNs for one at that moment is neither instant nor guaranteed.
  add column installation_id text;


-- ── Shapes ─────────────────────────────────────────────────────────────────

alter table public.push_subscriptions
  -- Uppercase hex, even length.
  --
  -- Both facts are read off the plugin rather than assumed: `PushNotifications`
  -- builds the string with `deviceToken.reduce("", {$0 + String(format:
  -- "%02X", $1)})`, which emits two uppercase hex digits per byte and therefore
  -- cannot produce a lowercase digit or an odd length.
  --
  -- No exact length is asserted. Tokens have been 32 bytes historically and are
  -- documented by Apple as variable; pinning a length would turn a future
  -- widening into a silent registration failure on every device at once. The
  -- upper bound is an abuse ceiling, not a specification.
  add constraint push_subscriptions_device_token_shape
    check (device_token is null
           or (device_token ~ '^[0-9A-F]+$'
               and char_length(device_token) % 2 = 0
               and char_length(device_token) between 2 and 512)),

  add constraint push_subscriptions_installation_id_shape
    check (installation_id is null or installation_id ~ '^[A-Za-z0-9_-]{8,64}$'),

  -- The discriminator. Each channel names every column it must have and every
  -- column it must not, so a row cannot drift into a half-populated state that
  -- reads as valid to one code path and invalid to another.
  add constraint push_subscriptions_channel_shape
    check (
      case channel
        when 'web_push' then
          endpoint is not null and p256dh is not null and auth_secret is not null
          and device_token is null and apns_environment is null and installation_id is null
        when 'apns' then
          device_token is not null and apns_environment is not null
          and installation_id is not null
          and endpoint is null and p256dh is null and auth_secret is null
      end
    );


-- ── Identity ───────────────────────────────────────────────────────────────
--
-- Two unique indexes, because an APNs row has two identities and they can move
-- independently.
--
-- The token is keyed WITH its environment, never alone. The same device running
-- a development build and later a TestFlight build presents different tokens,
-- but nothing guarantees two tokens from different environments cannot coincide
-- — they are opaque bytes from separate issuers — and a global unique(token)
-- would make one environment silently evict the other's row.

create unique index push_subscriptions_apns_token_key
  on public.push_subscriptions (device_token, apns_environment)
  where channel = 'apns';

-- The installation is unique on its own: one row per installed copy of the app,
-- whatever token it is currently reachable at and whoever is signed in to it.
create unique index push_subscriptions_apns_installation_key
  on public.push_subscriptions (installation_id)
  where channel = 'apns';

-- The dispatcher's lookup, mirroring push_subscriptions_user_enabled_idx but
-- carrying the columns an APNs send needs.
create index push_subscriptions_apns_enabled_idx
  on public.push_subscriptions (user_id)
  where enabled and channel = 'apns';


comment on column public.push_subscriptions.device_token is
  'APNs device token. A bearer credential, like endpoint/p256dh/auth_secret: '
  'never granted to any client role, readable only by the service-role '
  'dispatcher.';
comment on column public.push_subscriptions.installation_id is
  'App-generated, stable for the life of the installation. The identity that '
  'survives APNs token rotation and the one sign-out cleans up by.';


-- ── Register ───────────────────────────────────────────────────────────────

create or replace function public.register_apns_device(
  p_device_token text,
  p_environment public.apns_environment,
  p_installation_id text,
  p_device_label text default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor uuid := auth.uid();
  v_token text := upper(btrim(coalesce(p_device_token, '')));
  v_installation text := btrim(coalesce(p_installation_id, ''));
  v_id uuid;
begin
  if v_actor is null then
    raise exception 'AUTH_REQUIRED: no authenticated session' using errcode = '42501';
  end if;

  -- Rejected here as well as by the constraint, so a malformed token comes back
  -- as a named error the client can report rather than as a check violation.
  if v_token !~ '^[0-9A-F]+$'
     or char_length(v_token) % 2 <> 0
     or char_length(v_token) not between 2 and 512 then
    raise exception 'INVALID_DEVICE_TOKEN: not an APNs device token'
      using errcode = '22023';
  end if;

  if v_installation !~ '^[A-Za-z0-9_-]{8,64}$' then
    raise exception 'INVALID_INSTALLATION_ID: malformed installation id'
      using errcode = '22023';
  end if;

  -- ── Step one: release the token from any other installation ──────────────
  --
  -- Reached when the app's stored installation id is lost but the token is not:
  -- the webview's local storage was cleared, or the player deleted and
  -- reinstalled onto a device whose token APNs then reissued unchanged. The old
  -- row still names this exact device, so leaving it would send every
  -- notification twice.
  --
  -- Deleted rather than disabled. A disabled row would sit on the player's
  -- devices page as a second, permanently broken iPhone, and there is nothing
  -- they could do about it.
  delete from public.push_subscriptions
   where channel = 'apns'
     and device_token = v_token
     and apns_environment = p_environment
     and installation_id is distinct from v_installation;

  -- ── Step two: the installation's own row ─────────────────────────────────
  --
  -- Keyed on the installation, so a rotated token updates in place instead of
  -- accumulating. Ownership transfers on conflict, exactly as
  -- `register_push_subscription` does for a browser: whoever most recently
  -- granted permission on this device is who it belongs to, and the previous
  -- account's copy must not linger and keep receiving their alerts.
  insert into public.push_subscriptions (
    user_id, channel, device_token, apns_environment, installation_id, device_label
  )
  values (
    v_actor, 'apns', v_token, p_environment, v_installation,
    nullif(btrim(coalesce(p_device_label, '')), '')
  )
  on conflict (installation_id) where channel = 'apns' do update
    set user_id = v_actor,
        device_token = excluded.device_token,
        apns_environment = excluded.apns_environment,
        device_label = coalesce(excluded.device_label, public.push_subscriptions.device_label),
        enabled = true,
        disabled_reason = null,
        consecutive_failures = 0,
        last_seen_at = now()
  returning id into v_id;

  return v_id;
end;
$$;


-- ── Remove ─────────────────────────────────────────────────────────────────
--
-- Sign-out's counterpart to registration, addressed by installation rather than
-- by row id: at sign-out the app knows which installation it is, and knows it
-- from local storage without a round trip. It does not reliably know a current
-- device token — APNs may have rotated it while the app was closed — and it
-- does not know the subscription's id unless it kept one.
--
-- Scoped to the caller. Somebody else's installation id, guessed or stolen,
-- removes nothing.

create or replace function public.remove_apns_installation(p_installation_id text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor uuid := auth.uid();
begin
  if v_actor is null then
    raise exception 'AUTH_REQUIRED: no authenticated session' using errcode = '42501';
  end if;

  -- Idempotent, and silent about whether anything matched. Signing out twice,
  -- signing out from an installation the dispatcher already retired, or signing
  -- out with an id belonging to nobody are all simply "done" — a distinguishing
  -- error would tell a caller whether an installation id exists.
  delete from public.push_subscriptions
   where channel = 'apns'
     and installation_id = btrim(coalesce(p_installation_id, ''))
     and user_id = v_actor;
end;
$$;


-- ── Privileges ─────────────────────────────────────────────────────────────
--
-- A new function is EXECUTE-able by PUBLIC until told otherwise; the invariant
-- in `tests/db/schema.test.ts` fails the build if either of these is left that
-- way.

revoke execute on function
  public.register_apns_device(text, public.apns_environment, text, text) from public;
revoke execute on function public.remove_apns_installation(text) from public;

grant execute on function
  public.register_apns_device(text, public.apns_environment, text, text)
  to authenticated, service_role;
grant execute on function public.remove_apns_installation(text)
  to authenticated, service_role;

-- The column grant on push_subscriptions is an allow-list, so the four new
-- columns are unreadable by `authenticated` until named here. Only `channel`
-- is: the devices page has to say whether a row is a browser or the iOS app.
--
-- `device_token` is deliberately absent, for the same reason `endpoint`,
-- `p256dh` and `auth_secret` are — it is the credential. `apns_environment` and
-- `installation_id` are absent because nothing in the interface needs them, and
-- the smallest readable surface is the right default for a table whose rows
-- grant the ability to interrupt somebody's evening.
grant select (channel) on public.push_subscriptions to authenticated;
